openapi: 3.0.0
info:
  title: Town Council Clusters API
  description: API for managing complaint clusters - fetching triaged clusters and updating their review status
  version: 1.0.0
servers:
  - url: https://gsbpchneovtpqgnyfttp.supabase.co/rest/v1
    description: Supabase REST API

paths:
  /clusters:
    get:
      operationId: get_triaged_clusters
      summary: Get all triaged clusters ready for review
      description: Fetches all clusters with state='TRIAGED' from the database for review agent analysis
      parameters:
        - name: select
          in: query
          required: true
          schema:
            type: string
            default: "id,category,severity_score,zone_id,created_at,recurrence_count,priority_score,assigned_playbook,requires_human_review,last_action_at,description,complaint_count"
          description: Fields to select from clusters table
        - name: state
          in: query
          required: true
          schema:
            type: string
            default: "eq.TRIAGED"
          description: Filter by cluster state (eq.TRIAGED)
        - name: order
          in: query
          required: false
          schema:
            type: string
            default: "priority_score.desc.nullslast,severity_score.desc,created_at.asc"
          description: Sort order for results
      responses:
        '200':
          description: Array of triaged clusters
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    category:
                      type: string
                    severity_score:
                      type: integer
                    zone_id:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    recurrence_count:
                      type: integer
                    priority_score:
                      type: integer
                    assigned_playbook:
                      type: string
                    requires_human_review:
                      type: boolean
                    last_action_at:
                      type: string
                      format: date-time
                    description:
                      type: string
                    complaint_count:
                      type: integer
        '401':
          description: Unauthorized
        '500':
          description: Server error

    patch:
      operationId: review_cluster
      summary: Update cluster after review approval
      description: Updates a cluster's state to REVIEWED with assigned playbook and priority score
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
          description: Filter by cluster ID (format eq.{uuid})
          example: "eq.c1000001-0000-0000-0000-000000000008"
        - name: Prefer
          in: header
          required: false
          schema:
            type: string
            default: "return=representation"
          description: Return the updated object
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - state
                - assigned_playbook
                - priority_score
                - review_notes
                - requires_human_review
              properties:
                state:
                  type: string
                  enum: [REVIEWED]
                  default: REVIEWED
                  description: New state after review
                assigned_playbook:
                  type: string
                  enum:
                    - standard_cleanup
                    - deep_clean_protocol
                    - specialist_dispatch
                    - bin_washdown
                    - surveillance_monitoring
                    - manual_review_required
                  description: Playbook to assign based on category and severity
                  example: "specialist_dispatch"
                priority_score:
                  type: integer
                  minimum: 0
                  maximum: 150
                  description: Calculated priority score (with fairness boosts)
                  example: 110
                review_notes:
                  type: string
                  description: Justification for the review decision
                  example: "Critical pest issue (dead rat). Silent Zone boost applied (1 complaint, severity 5). Requires specialist pest control dispatch."
                requires_human_review:
                  type: boolean
                  description: Whether this cluster needs human oversight
                  example: true
                last_action_at:
                  type: string
                  format: date-time
                  description: Timestamp of last action (auto-set to now)
      responses:
        '200':
          description: Updated cluster object
          content:
            application/json:
              schema:
                type: object
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Cluster not found
        '500':
          description: Server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []
